export const MAX_DAILY_CHARACTER_GUESSES = 15;
export const MAX_UNLIMITED_CHARACTER_GUESSES = 10;
export const MAX_DAILY_SONG_GUESSES = 15;
export const MAX_UNLIMITED_SONG_GUESSES = 10;
export const MAX_DAILY_QUOTE_GUESSES = 15;
export const MAX_UNLIMITED_QUOTE_GUESSES = 10;
export const MAX_DAILY_SILHOUETTE_GUESSES = 15;
export const MAX_UNLIMITED_SILHOUETTE_GUESSES = 10;
export const MAX_DAILY_EMOJI_GUESSES = 15;
export const MAX_UNLIMITED_EMOJI_GUESSES = 10;

export const INITIAL_REVEAL_SILHOUETTE = 8;